### ISSUE TITLE
Pymanoid versions mismatch

### ISSUE THREAD

**Issue by ghost** [stephane-caron/dynamic-walking#3]
Hello Dr.Caron

I have installed your fip-walking package and as you know it has Non-linear codes in its pymanoid codes and you have mentioned in installation instruction that the pymanoid packages should be same. But the latest pymanoid package doesn't have those Non-linear codes. For example I get this error all the time:
    from pymanoid.optim import NonlinearProgram

ImportError: No module named optim

And the reason is that my current installed pymanoid which is the latest one doesn't contain non-linear packages and codes such as nmpc.py or optim.py. So should I downgrade my current installed pymanoid and use the package which is apparently for a couple of years ago or is there any other options?! 

Thank You

**Comment by stephane-caron** [comment]
The ``NonlinearProgram`` class was moved to a different file. You can use ``grep`` to find it:
```
$ cd pymanoid/pymanoid
$ grep -r "Nonlinear" .                                                                 1 ↵
./nlp.py:class NonlinearProgram(object):
```
Note that if you have a new version of pymanoid installed on your system, make sure to clone submodules (using a ``--recursive`` git clone) and run the ``walk.py`` script from this repository. This way, it will import the submodule rather than system-wide pymanoid version.
